@startuml
'https://plantuml.com/class-diagram


package InspectionPlanWorker {

  class InspectionPlanWorker {
    ..props ..
    inspectionPlan: IInspectionPlanFromDB
    ..consts ..
    finishedInspectionPlan: IInspectionPlanInProgress
    serialNumber: string
    finalSerialNumber: string
    ..functions ..
    showSaveToPDFButton(bool: boolean): void
    saveSerialNumber(e:any): void
    serialNumberInput(e:any): void
  }


  class InspectionPlanWorkerTable {
    ..props ..
    valuesAndTolerances: IValuesAndTolerances[]
    onEveryValueEntered: (bool: boolean, finishedValsAndTols: IValuesAndTolerances[]): void
    ..consts ..
    valuesAndTolsInProgress: IValuesAndTolerancesInProgress[]
    ..functions ..
    useEffect()
    onValueSaveHandler(index: number, measuredValue: number)
    checkIfEveryValueIsEntered()
  }



  class InspectionPlanWorkerTableRow {
    ..props ..
    index: number
    valueToBeMeasured: number
    tolerance: number
    onValueSave: (index: number, measuredValue: number):void
    ..consts ..
    enteredValue: number
    numberEntered: boolean
    passfail: boolean
    passfailDisplayText: string
    ..functions ..
    useEffect();
    onEnterHandler(input :string)
    handleChangeEnteredValue(e: any)
    calculateTolerance(valueMeasured: number, tolerance: [number,number], valueToBeMeasured: number): boolean
  }

  InspectionPlanWorker --> InspectionPlanWorkerTable: > uses
  InspectionPlanWorkerTable --> InspectionPlanWorkerTableRow: > uses


}

InspectionPlanWorker --> PDFExport: > uses
InspectionPlanWorkerTableRow --> ReadonlyInput: > uses
InspectionPlanWorkerTableRow --> IconDisplay: > uses

@enduml
