@startuml (PDFExport component)

class PDFexport {
  ..props ..
  inspectionPlan: IInspectionPlanInProgress
  serialNumber?: string
  ..consts ..
  nameOfInspector: string
  ..functions ..
  onClickHandler(): void
}

@enduml
