@startuml
'https://plantuml.com/class-diagram

class Worker {
  .. Start consts ..
  pageStatus
  history
  currentUserState
  openLoginPage()
  setPageStatus()
  .. End consts ..
  contentSwitch()
}

@enduml
components
