@startuml
'https://plantuml.com/class-diagram

interface IInspectionPlanInProgress extends IInspectionPlanFromDB {
  serialnumber?: string
  valuesAndTolerancesInProgress?: IValuesAndTolerancesInProgress[];
}

@enduml
